Implement ssh_dmz_dns_from_internal_network feature
net-tester/examples pull request #29
Opened 2017-01-12 07:11 UTC by qb0C80aE

2017-02-06 05:58 UTC, yasuhito requested changes
例の空白の修正と、ステップ汎用化についてレビューしました。よろしくおねがいしますー!

2017-02-06 05:58 UTC, yasuhito commented on features/ssh_dmz_dns_from_internal_network.feature
> +Feature: ヨーヨーダイン社内部からDMZのDNSサーバにsshでログイン
この feature 全体に、例の空白をおねがいします。

2017-02-06 05:58 UTC, yasuhito commented on features/ssh_dmz_dns_from_internal_network.feature
> +    Then ヨーヨーダイン社からDMZ内のDNSサーバにsshでログイン成功
シナリオの後半で、同じ修飾子が繰り返し出てくるので読みづらくなってると思います。

>   Scenario: ヨーヨーダイン社からDMZ内のDNSサーバにsshでログイン
    Given ヨーヨーダイン社内部のクライアント
    And ヨーヨーダイン社のDMZ内のDNSサーバ
    When ヨーヨーダイン社からDMZ内のDNSサーバにsshでログイン
    Then ヨーヨーダイン社からDMZ内のDNSサーバにsshでログイン成功

たとえばこんな感じにできれば読みやすくなります。ステップの中でインスタンス変数をうまく使って、汎用化できないでしょうか。

```
  Scenario: ヨーヨーダイン社から DMZ 内の DNS サーバに ssh でログイン
    Given ヨーヨーダイン社内部の ssh クライアントサーバ
    And ヨーヨーダイン社 DMZ 内の DNS サーバ
    When DNS サーバに ssh ログイン
    Then ログインに成功
```

2017-02-09 06:59 UTC, qb0C80aE commented
修正してみました。

2017-02-09 07:17 UTC, yasuhito requested changes
軽微な修正をおねがいします!

2017-02-09 07:17 UTC, yasuhito commented on features/ssh_dmz_dns_from_internal_network.feature
> +Feature: ヨーヨーダイン社内部の PC から DMZ 内の DNS サーバに ssh でログイン
ここは「〜ログイン」はなくても意味は通じそう?
「ヨーヨーダイン社内部の PC から DMZ 内の DNS サーバに ssh」

2017-02-09 07:17 UTC, yasuhito commented on features/ssh_dmz_dns_from_internal_network.feature
> +  なぜならメンテナンス業務に必要だから
「なぜなら DNS をメンテナンスするから」のほうが平易でしょうか。

2017-02-09 07:32 UTC, qb0C80aE commented
修正しました！

2017-02-09 07:34 UTC, yasuhito approved these changes

2017-02-09 07:34 UTC, merged